// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mms.Infrastructure.Persistence;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Mms.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(MmsDbContext))]
    partial class MmsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Mms.Domain.Entities.AttendanceRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AttendCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AttendanceType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CancelReason")
                        .HasColumnType("text");

                    b.Property<DateTime>("CheckedInAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("GiftReceived")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("GiftReceivedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("GiftReceivedBy")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid>("MeetingId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("OperatorUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("PhoneSource")
                        .HasColumnType("text");

                    b.Property<string>("PhysicalAttendeeIdNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("PhysicalAttendeeName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("PosTerminal")
                        .HasColumnType("text");

                    b.Property<Guid>("ShareholderId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<uint>("Xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("AttendCode")
                        .IsUnique();

                    b.HasIndex("PhysicalAttendeeIdNumber");

                    b.HasIndex("ShareholderId");

                    b.HasIndex("MeetingId", "ShareholderId")
                        .IsUnique()
                        .HasFilter("\"IsActive\" = true");

                    b.ToTable("attendance_records", (string)null);
                });

            modelBuilder.Entity("Mms.Domain.Entities.AttendanceSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ConfirmedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("MeetingId")
                        .HasColumnType("uuid");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<decimal>("PercentageQuorum")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<DateTime>("SnapshotAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("SnapshotType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("TotalAttendingShareholders")
                        .HasColumnType("integer");

                    b.Property<long>("TotalAttendingShares")
                        .HasColumnType("bigint");

                    b.Property<int>("TotalBallotsIssued")
                        .HasColumnType("integer");

                    b.Property<int>("TotalPhysicalAttendees")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("MeetingId", "SnapshotType")
                        .IsUnique();

                    b.ToTable("attendance_snapshots", (string)null);
                });

            modelBuilder.Entity("Mms.Domain.Entities.AuditLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<string>("Actor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Detail")
                        .HasColumnType("jsonb");

                    b.Property<Guid?>("EntityId")
                        .HasColumnType("uuid");

                    b.Property<string>("EntityType")
                        .HasColumnType("text");

                    b.Property<Guid?>("MeetingId")
                        .HasColumnType("uuid");

                    b.Property<string>("PosTerminal")
                        .HasColumnType("text");

                    b.Property<DateTime>("Ts")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("MeetingId", "Ts");

                    b.ToTable("audit_logs", (string)null);
                });

            modelBuilder.Entity("Mms.Domain.Entities.Ballot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AttendCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("AttendanceRecordId")
                        .HasColumnType("uuid");

                    b.Property<string>("BallotType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("BulkApproved")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<long>("DirectShares")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("InvalidatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("InvalidationReason")
                        .HasColumnType("text");

                    b.Property<bool>("IsSplitBallot")
                        .HasColumnType("boolean");

                    b.Property<Guid>("MeetingId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("OperatorUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ParentBallotId")
                        .HasColumnType("uuid");

                    b.Property<string>("PosTerminal")
                        .HasColumnType("text");

                    b.Property<DateTime?>("PrintedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("ProxyRepresentationNote")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<long>("ProxyShares")
                        .HasColumnType("bigint");

                    b.Property<bool>("ReprintNeeded")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ShareholderId")
                        .HasColumnType("uuid");

                    b.Property<int?>("SplitSequence")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<long>("VotingShares")
                        .HasColumnType("bigint");

                    b.Property<uint>("Xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("AttendCode")
                        .IsUnique();

                    b.HasIndex("ParentBallotId");

                    b.HasIndex("ShareholderId");

                    b.HasIndex("AttendanceRecordId", "BallotType");

                    b.HasIndex("MeetingId", "Status");

                    b.ToTable("ballots", (string)null);
                });

            modelBuilder.Entity("Mms.Domain.Entities.BallotGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AttendanceRecordId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("BallotId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<int>("GroupNumber")
                        .HasColumnType("integer");

                    b.Property<Guid>("SourceShareholderId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("BallotId");

                    b.HasIndex("SourceShareholderId");

                    b.HasIndex("AttendanceRecordId", "SourceShareholderId")
                        .IsUnique();

                    b.ToTable("ballot_groups", (string)null);
                });

            modelBuilder.Entity("Mms.Domain.Entities.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<long>("CharterCapital")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("EnglishName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Fax")
                        .HasColumnType("text");

                    b.Property<string>("LegalRepName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LegalRepTitle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LogoPath")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .HasColumnType("text");

                    b.Property<string>("SealImagePath")
                        .HasColumnType("text");

                    b.Property<string>("ShortName")
                        .HasColumnType("text");

                    b.Property<string>("SignatureImagePath")
                        .HasColumnType("text");

                    b.Property<string>("StockCode")
                        .HasColumnType("text");

                    b.Property<string>("StockExchange")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("TaxCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("TotalSharesIssued")
                        .HasColumnType("bigint");

                    b.Property<long>("TotalVotingShares")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Website")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("TaxCode")
                        .IsUnique();

                    b.ToTable("companies", (string)null);
                });

            modelBuilder.Entity("Mms.Domain.Entities.ElectionVote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BallotId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("EnteredAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("EnteredBy")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MeetingCandidateId")
                        .HasColumnType("uuid");

                    b.Property<long>("Points")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("MeetingCandidateId");

                    b.HasIndex("BallotId", "MeetingCandidateId")
                        .IsUnique();

                    b.ToTable("election_votes", (string)null);
                });

            modelBuilder.Entity("Mms.Domain.Entities.InvitationLetter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CodeMarkType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("DispatchedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("MeetingId")
                        .HasColumnType("uuid");

                    b.Property<string>("ShareholderAddress")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ShareholderIdNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ShareholderName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("ShareholderPhone")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<long>("SharesTotal")
                        .HasColumnType("bigint");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<DateTime?>("StatusUpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("TemplateId")
                        .HasColumnType("uuid");

                    b.Property<string>("TrackingCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp without time zone");

                    b.Property<long>("VotingRights")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("MeetingId");

                    b.HasIndex("TrackingCode")
                        .HasFilter("\"TrackingCode\" IS NOT NULL");

                    b.HasIndex("MeetingId", "Status");

                    b.ToTable("invitation_letters", (string)null);
                });

            modelBuilder.Entity("Mms.Domain.Entities.Meeting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Chairman")
                        .HasColumnType("text");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("DefaultPrintMode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("GiftEnabled")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("MeetingDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("MeetingType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<decimal>("QuorumThreshold")
                        .HasPrecision(5, 4)
                        .HasColumnType("numeric(5,4)");

                    b.Property<DateOnly>("RecordDate")
                        .HasColumnType("date");

                    b.Property<string>("Secretary")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("TotalVotingShares")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("meetings", (string)null);
                });

            modelBuilder.Entity("Mms.Domain.Entities.MeetingCandidate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("BirthYear")
                        .HasColumnType("integer");

                    b.Property<string>("CandidateBoard")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CurrentPosition")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("MeetingId")
                        .HasColumnType("uuid");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<int>("NumberOfSeats")
                        .HasColumnType("integer");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("MeetingId");

                    b.ToTable("meeting_candidates", (string)null);
                });

            modelBuilder.Entity("Mms.Domain.Entities.MeetingResolution", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("ApprovalThreshold")
                        .HasPrecision(5, 4)
                        .HasColumnType("numeric(5,4)");

                    b.Property<string>("Content")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<Guid>("MeetingId")
                        .HasColumnType("uuid");

                    b.Property<string>("ResolutionType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("MeetingId");

                    b.ToTable("meeting_resolutions", (string)null);
                });

            modelBuilder.Entity("Mms.Domain.Entities.MeetingTemplateConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CodeType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("MeetingId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TemplateId")
                        .HasColumnType("uuid");

                    b.Property<string>("TemplateType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("TemplateId");

                    b.HasIndex("MeetingId", "TemplateType")
                        .IsUnique();

                    b.ToTable("meeting_template_configs", (string)null);
                });

            modelBuilder.Entity("Mms.Domain.Entities.Proxy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CancellationReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Detail")
                        .HasColumnType("text");

                    b.Property<string>("GranteeIdNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("GranteeName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("GranteeRecipientId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("GranteeShareholderId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("GrantorId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("InvalidatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("MeetingId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly?>("ProxyDate")
                        .HasColumnType("date");

                    b.Property<string>("ProxyType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ScanUrl")
                        .HasColumnType("text");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("Shares")
                        .HasColumnType("bigint");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("SupersededById")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("GranteeRecipientId");

                    b.HasIndex("GranteeShareholderId");

                    b.HasIndex("GrantorId");

                    b.HasIndex("Status");

                    b.HasIndex("SupersededById");

                    b.HasIndex("MeetingId", "GrantorId");

                    b.ToTable("proxies", (string)null);
                });

            modelBuilder.Entity("Mms.Domain.Entities.ProxyRecipient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("IdNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Organization")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("PhoneUpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Position")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("IdNumber");

                    b.ToTable("proxy_recipients", (string)null);
                });

            modelBuilder.Entity("Mms.Domain.Entities.Shareholder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly?>("IdIssueDate")
                        .HasColumnType("date");

                    b.Property<string>("IdNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ImportedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("InvestorCode")
                        .HasColumnType("text");

                    b.Property<bool>("IsForeign")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsOrganization")
                        .HasColumnType("boolean");

                    b.Property<Guid>("MeetingId")
                        .HasColumnType("uuid");

                    b.Property<string>("Nationality")
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .HasColumnType("text");

                    b.Property<long>("RightsDeposit")
                        .HasColumnType("bigint");

                    b.Property<long>("RightsNonDeposit")
                        .HasColumnType("bigint");

                    b.Property<long>("SharesDeposit")
                        .HasColumnType("bigint");

                    b.Property<long>("SharesNonDeposit")
                        .HasColumnType("bigint");

                    b.Property<long>("SharesTotal")
                        .HasColumnType("bigint");

                    b.Property<string>("Sid")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<long>("VotingRights")
                        .HasColumnType("bigint");

                    b.Property<string>("VsdcRow")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("MeetingId", "DisplayOrder");

                    b.HasIndex("MeetingId", "IdNumber");

                    b.ToTable("shareholders", (string)null);
                });

            modelBuilder.Entity("Mms.Domain.Entities.TallySnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ConfirmedBy1")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ConfirmedBy2")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<long>("DenominatorShares")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("LockedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("MeetingId")
                        .HasColumnType("uuid");

                    b.Property<string>("SnapshotType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("TotalBallotCounted")
                        .HasColumnType("integer");

                    b.Property<int>("TotalBallotInvalid")
                        .HasColumnType("integer");

                    b.Property<int>("TotalBallotIssued")
                        .HasColumnType("integer");

                    b.Property<int>("TotalBallotNotReturned")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("MeetingId", "SnapshotType")
                        .IsUnique();

                    b.ToTable("tally_snapshots", (string)null);
                });

            modelBuilder.Entity("Mms.Domain.Entities.Template", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("FieldsConfig")
                        .HasColumnType("text");

                    b.Property<string>("FilePath")
                        .HasColumnType("text");

                    b.Property<long?>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<string>("HtmlContent")
                        .HasColumnType("text");

                    b.Property<bool>("IsFinalized")
                        .HasColumnType("boolean");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<float>("MarginBottom")
                        .HasColumnType("real");

                    b.Property<float>("MarginLeft")
                        .HasColumnType("real");

                    b.Property<float>("MarginRight")
                        .HasColumnType("real");

                    b.Property<float>("MarginTop")
                        .HasColumnType("real");

                    b.Property<Guid?>("MeetingId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SelectedTokens")
                        .HasColumnType("text");

                    b.Property<int>("TemplateType")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("UploadedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("UploadedBy")
                        .HasColumnType("uuid");

                    b.Property<bool>("UseSignatureAndSeal")
                        .HasColumnType("boolean");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MeetingId");

                    b.ToTable("Templates");
                });

            modelBuilder.Entity("Mms.Domain.Entities.VoteResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BallotId")
                        .HasColumnType("uuid");

                    b.Property<bool>("BulkApproved")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("EnteredAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("EnteredBy")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MeetingResolutionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("VoteChoice")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("VotingShares")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("MeetingResolutionId");

                    b.HasIndex("BallotId", "MeetingResolutionId")
                        .IsUnique();

                    b.ToTable("vote_results", (string)null);
                });

            modelBuilder.Entity("Mms.Infrastructure.Identity.ApplicationRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Mms.Infrastructure.Identity.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("MustChangePassword")
                        .HasColumnType("boolean");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Mms.Infrastructure.Identity.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("Mms.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("Mms.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Mms.Infrastructure.Identity.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mms.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("Mms.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Mms.Domain.Entities.AttendanceRecord", b =>
                {
                    b.HasOne("Mms.Domain.Entities.Meeting", "Meeting")
                        .WithMany()
                        .HasForeignKey("MeetingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Mms.Domain.Entities.Shareholder", "Shareholder")
                        .WithMany()
                        .HasForeignKey("ShareholderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Meeting");

                    b.Navigation("Shareholder");
                });

            modelBuilder.Entity("Mms.Domain.Entities.AttendanceSnapshot", b =>
                {
                    b.HasOne("Mms.Domain.Entities.Meeting", "Meeting")
                        .WithMany()
                        .HasForeignKey("MeetingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Meeting");
                });

            modelBuilder.Entity("Mms.Domain.Entities.Ballot", b =>
                {
                    b.HasOne("Mms.Domain.Entities.AttendanceRecord", "AttendanceRecord")
                        .WithMany("Ballots")
                        .HasForeignKey("AttendanceRecordId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Mms.Domain.Entities.Meeting", "Meeting")
                        .WithMany()
                        .HasForeignKey("MeetingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Mms.Domain.Entities.Ballot", "ParentBallot")
                        .WithMany()
                        .HasForeignKey("ParentBallotId");

                    b.HasOne("Mms.Domain.Entities.Shareholder", "Shareholder")
                        .WithMany()
                        .HasForeignKey("ShareholderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AttendanceRecord");

                    b.Navigation("Meeting");

                    b.Navigation("ParentBallot");

                    b.Navigation("Shareholder");
                });

            modelBuilder.Entity("Mms.Domain.Entities.BallotGroup", b =>
                {
                    b.HasOne("Mms.Domain.Entities.AttendanceRecord", "AttendanceRecord")
                        .WithMany("BallotGroups")
                        .HasForeignKey("AttendanceRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mms.Domain.Entities.Ballot", "Ballot")
                        .WithMany()
                        .HasForeignKey("BallotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Mms.Domain.Entities.Shareholder", "SourceShareholder")
                        .WithMany()
                        .HasForeignKey("SourceShareholderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AttendanceRecord");

                    b.Navigation("Ballot");

                    b.Navigation("SourceShareholder");
                });

            modelBuilder.Entity("Mms.Domain.Entities.ElectionVote", b =>
                {
                    b.HasOne("Mms.Domain.Entities.Ballot", "Ballot")
                        .WithMany("ElectionVotes")
                        .HasForeignKey("BallotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Mms.Domain.Entities.MeetingCandidate", "MeetingCandidate")
                        .WithMany()
                        .HasForeignKey("MeetingCandidateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Ballot");

                    b.Navigation("MeetingCandidate");
                });

            modelBuilder.Entity("Mms.Domain.Entities.InvitationLetter", b =>
                {
                    b.HasOne("Mms.Domain.Entities.Meeting", "Meeting")
                        .WithMany("InvitationLetters")
                        .HasForeignKey("MeetingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Meeting");
                });

            modelBuilder.Entity("Mms.Domain.Entities.Meeting", b =>
                {
                    b.HasOne("Mms.Domain.Entities.Company", "Company")
                        .WithMany("Meetings")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Mms.Domain.Entities.MeetingCandidate", b =>
                {
                    b.HasOne("Mms.Domain.Entities.Meeting", "Meeting")
                        .WithMany("Candidates")
                        .HasForeignKey("MeetingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Meeting");
                });

            modelBuilder.Entity("Mms.Domain.Entities.MeetingResolution", b =>
                {
                    b.HasOne("Mms.Domain.Entities.Meeting", "Meeting")
                        .WithMany("Resolutions")
                        .HasForeignKey("MeetingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Meeting");
                });

            modelBuilder.Entity("Mms.Domain.Entities.MeetingTemplateConfig", b =>
                {
                    b.HasOne("Mms.Domain.Entities.Meeting", "Meeting")
                        .WithMany("TemplateConfigs")
                        .HasForeignKey("MeetingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mms.Domain.Entities.Template", "Template")
                        .WithMany()
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Meeting");

                    b.Navigation("Template");
                });

            modelBuilder.Entity("Mms.Domain.Entities.Proxy", b =>
                {
                    b.HasOne("Mms.Domain.Entities.ProxyRecipient", "GranteeRecipient")
                        .WithMany()
                        .HasForeignKey("GranteeRecipientId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Mms.Domain.Entities.Shareholder", "GranteeShareholder")
                        .WithMany()
                        .HasForeignKey("GranteeShareholderId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Mms.Domain.Entities.Shareholder", "Grantor")
                        .WithMany()
                        .HasForeignKey("GrantorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Mms.Domain.Entities.Meeting", "Meeting")
                        .WithMany()
                        .HasForeignKey("MeetingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Mms.Domain.Entities.Proxy", "SupersededBy")
                        .WithMany()
                        .HasForeignKey("SupersededById");

                    b.Navigation("GranteeRecipient");

                    b.Navigation("GranteeShareholder");

                    b.Navigation("Grantor");

                    b.Navigation("Meeting");

                    b.Navigation("SupersededBy");
                });

            modelBuilder.Entity("Mms.Domain.Entities.Shareholder", b =>
                {
                    b.HasOne("Mms.Domain.Entities.Meeting", "Meeting")
                        .WithMany("Shareholders")
                        .HasForeignKey("MeetingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Meeting");
                });

            modelBuilder.Entity("Mms.Domain.Entities.TallySnapshot", b =>
                {
                    b.HasOne("Mms.Domain.Entities.Meeting", "Meeting")
                        .WithMany()
                        .HasForeignKey("MeetingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Meeting");
                });

            modelBuilder.Entity("Mms.Domain.Entities.Template", b =>
                {
                    b.HasOne("Mms.Domain.Entities.Meeting", "Meeting")
                        .WithMany()
                        .HasForeignKey("MeetingId");

                    b.Navigation("Meeting");
                });

            modelBuilder.Entity("Mms.Domain.Entities.VoteResult", b =>
                {
                    b.HasOne("Mms.Domain.Entities.Ballot", "Ballot")
                        .WithMany("VoteResults")
                        .HasForeignKey("BallotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Mms.Domain.Entities.MeetingResolution", "MeetingResolution")
                        .WithMany()
                        .HasForeignKey("MeetingResolutionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Ballot");

                    b.Navigation("MeetingResolution");
                });

            modelBuilder.Entity("Mms.Domain.Entities.AttendanceRecord", b =>
                {
                    b.Navigation("BallotGroups");

                    b.Navigation("Ballots");
                });

            modelBuilder.Entity("Mms.Domain.Entities.Ballot", b =>
                {
                    b.Navigation("ElectionVotes");

                    b.Navigation("VoteResults");
                });

            modelBuilder.Entity("Mms.Domain.Entities.Company", b =>
                {
                    b.Navigation("Meetings");
                });

            modelBuilder.Entity("Mms.Domain.Entities.Meeting", b =>
                {
                    b.Navigation("Candidates");

                    b.Navigation("InvitationLetters");

                    b.Navigation("Resolutions");

                    b.Navigation("Shareholders");

                    b.Navigation("TemplateConfigs");
                });
#pragma warning restore 612, 618
        }
    }
}
